Repository afes-website/back, pull requests merged in 2020-03, with the labels that each got.

#18 #17: timestampの項にデフォルト値をセット
  database/migrations/2020_02_16_035148_create_revisions_table.php
  database/migrations/2020_02_16_072026_create_articles_table.php
Labels: bug

#16 #15: JWT_SECRETとAPP_KEYをまとめた
  .env.example
  app/Http/Controllers/AdminAuthController.php
  app/Http/Controllers/WriterAuthController.php
  app/Providers/AdminAuthServiceProvider.php
  app/Providers/WriterAuthServiceProvider.php
Labels: enhancement

#21 #12: 自動テスト/デプロイ
  .github/workflows/deploy_product.yml
  .github/workflows/deploy_test.yml
  .github/workflows/test_pull.yml
Labels: enhancement

#22 デプロイのエラー修正
  .github/workflows/deploy_product.yml
  .github/workflows/deploy_test.yml
Labels: bug

#26 #25: ブログ検索
  app/Http/Controllers/BlogArticleController.php
Labels: enhancement

#24 #23: 画像アップロード
  app/Http/Controllers/ImageController.php
  app/Models/Image.php
  bootstrap/app.php
  composer.json
  composer.lock
  database/migrations/2020_03_02_182021_create_images_table.php
  routes/web.php
  tests/ImageTest.php
Labels: enhancement

#30 #29 slack通知
  .env.example
  app/Http/Controllers/BlogArticleController.php
  app/Http/Controllers/BlogRevisionController.php
  app/Http/Controllers/ImageController.php
  app/SlackNotify.php
  phpunit.xml
Labels: enhancement

#32 [hotfix] #31: 画像contentの型がLONGBLOBじゃなかった
  database/migrations/2020_03_11_021218_expand_images_blob.php
Labels: bug

#28 improve tests
  tests/AdminAuthJwtTest.php
  tests/BlogArticleTest.php
  tests/BlogRevisionTest.php
  tests/ExampleTest.php
  tests/WriterAuthJwtTest.php
Labels: test

#39 #37 revision/articleがauthorを返すように
  app/Http/Controllers/BlogRevisionController.php
  app/Http/Resources/RevisionResource.php
  tests/BlogRevisionTest.php
Labels: bug
