Repository afes-website/back, pull requests merged in 2020-10, with the labels that each got.

#102 #98 文化祭オンライン展示
  app/Http/Controllers/DraftController.php
  app/Http/Controllers/ExhibitionController.php
  app/Http/Middleware/Authenticate.php
  app/Http/Resources/DraftCommentResource.php
  app/Http/Resources/DraftResource.php
  app/Http/Resources/ExhibitionResource.php
  app/Http/Resources/UserResource.php
  app/Libs/Boolean.php
  app/Models/Draft.php
  app/Models/DraftComments.php
  app/Models/Exhibition.php
  app/Models/User.php
  app/SlackNotify.php
  database/factories/ModelFactory.php
  database/migrations/2020_09_27_104959_create_exhibitions_table.php
  database/migrations/2020_09_27_105115_create_drafts_table.php
  database/migrations/2020_09_27_105134_create_draft_comments_table.php
  database/migrations/2020_09_29_113041_add_teacher_perm_to_users.php
  database/migrations/2020_09_30_043438_add_user_id_column.php
  database/migrations/2020_10_05_232231_add_category_to_exh.php
  routes/web.php
  tests/AuthJwtTest.php
  tests/DraftTest.php
  tests/ExhibitionTest.php
Labels: enhancement

#108 fix: model exist checking
  app/Http/Controllers/ExhibitionController.php
  composer.json
Labels: HotFix

#109 model exist checking to dev
  app/Http/Controllers/ExhibitionController.php
  composer.json
Labels: HotFix

#112 #111 Contentが長い文字列に対応できるように
  composer.json
  database/migrations/2020_10_26_072735_change_content_column_in_draft.php
Labels: HotFix, Release

#113 #111 Contentが長い文字列に対応できるように to Dev
  composer.json
  database/migrations/2020_10_26_072735_change_content_column_in_draft.php
Labels: HotFix, bug

#115 respond room_id
  app/Http/Controllers/ExhibitionController.php
  app/Http/Resources/ExhibitionResource.php
  database/migrations/2020_10_29_220915_add_roomid_column.php
Labels: enhancement

#116 release/2.2.3
  app/Http/Controllers/ExhibitionController.php
  app/Http/Resources/ExhibitionResource.php
  composer.json
  composer.lock
  database/migrations/2020_10_29_220915_add_roomid_column.php
Labels: Release

#117 release 2.2.3 to dev
  composer.json
Labels: Release
