Repository afes-website/back, pull requests merged in 2021-03, with the labels that each got.

#142 #141 すべての Test で actingAs を使うようにした
  database/factories/ModelFactory.php
  tests/AuthJwtTest.php
  tests/BlogArticleTest.php
  tests/BlogRevisionTest.php
  tests/DraftTest.php
  tests/ImageTest.php
  tests/OGImageTest.php
Labels: enhancement

#147 fix: add migrations for target of phpcs
  database/migrations/2020_02_16_035148_create_revisions_table.php
  database/migrations/2020_02_16_072026_create_articles_table.php
  database/migrations/2020_03_02_182021_create_images_table.php
  database/migrations/2020_03_11_021218_expand_images_blob.php
  database/migrations/2020_06_21_024650_add_handlename_to_article_and_revision.php
  database/migrations/2020_08_24_055926_create_new_users_table.php
  database/migrations/2020_08_24_071317_transfer_users_record.php
  database/migrations/2020_09_27_104959_create_exhibitions_table.php
  database/migrations/2020_09_27_105115_create_drafts_table.php
  database/migrations/2020_09_27_105134_create_draft_comments_table.php
  database/migrations/2020_09_29_113041_add_teacher_perm_to_users.php
  database/migrations/2020_09_30_043438_add_user_id_column.php
  database/migrations/2020_10_05_232231_add_category_to_exh.php
  database/migrations/2020_10_26_072735_change_content_column_in_draft.php
  phpcs.xml
Labels: enhancement

#149 #148 ext-jsonをcomposer.jsonに追加した
  composer.json
Labels: dependencies

#146 外部キー制約を追加
  database/migrations/2021_03_12_111147_fix_relationship_types.php
  database/migrations/2021_03_12_223739_add_foreign_constraint.php
  database/migrations/2021_03_13_173753_add_draft_comment_author_constraint.php
Labels: enhancement

#154 テストにmysqlを使用
  .github/workflows/test_pull.yml
  .gitignore
  app/Providers/AppServiceProvider.php
  bootstrap/app.php
  composer.json
  database/factories/ModelFactory.php
  database/migrations/2020_10_26_072735_change_content_column_in_draft.php
  database/migrations/2021_03_12_223739_add_foreign_constraint.php
  phpunit.xml
  tests/BlogArticleTest.php
  tests/BlogRevisionTest.php
  tests/DraftTest.php
  tests/ExhibitionTest.php
  tests/TestCase.php
Labels: test
